[package]
edition      = "2024"
name         = "roll"
rust-version = "1.88"
version      = "0.1.1"

[[bin]]
name = "roll"
path = "./src/main.rs"

[dev-dependencies]
embedded-test = "0.7.0"

[[test]]
name = "init_test"
harness = false

[features]
defmt = [
    "dep:defmt",
    "esp-hal/defmt",
    "esp-rtos/defmt",
    "esp-bootloader-esp-idf/defmt",
    "embassy-executor/defmt",
    "embassy-time/defmt",
    "panic-rtt-target/defmt",
    "rtt-target/defmt",
]
# future support for other targets
esp32c6 = []

[dependencies]
# Base dependencies without hardcoded defmt features
esp-hal  = { version = "~1.1.0", features = ["esp32c6", "unstable"] }
esp-rtos = { version = "0.3.0", features = ["embassy", "esp32c6"] }
esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32c6"] }

embassy-executor = { version = "0.10.0" }
embassy-time     = { version = "0.5.0" }
panic-rtt-target = { version = "0.2.0" }
rtt-target       = { version = "0.6.2" }

# Optional defmt crate
defmt = { version = "1.1.1", optional = true }

critical-section = "1.2.0"
static_cell      = "2.1.1"

[profile.dev]
opt-level     = 's'
debug         = true
strip         = "none"
lto           = false
panic         = 'abort'
codegen-units = 16

[profile.release]
codegen-units = 1
debug         = 0
lto           = 'fat'
opt-level     = 3
strip         = true
