name: Rust CI

on:
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - "**.toml"
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths:
      - "**.rs"
      - "**.toml"
      - '.github/workflows/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: riscv32imac-unknown-none-elf
          components: clippy


      - name: Cache Rust
        id: cargo-cache
        uses: actions/cache@v6
        with:
            path: |
                ~/.cargo/registry
                ~/.cargo/git
                ~/.cargo/bin
                target
            key: ${{ runner.os }}-rust-stable-riscv32imac-${{ hashFiles('**/Cargo.lock') }}

            restore-keys: |
                ${{ runner.os }}-rust-stable-riscv32imac-

      - name: Install cargo-audit
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        run: cargo install cargo-audit

      - name: Build debug + features
        run: cargo build --target riscv32imac-unknown-none-elf --verbose --profile dev --all-features

      - name: Build Release
        run: cargo build --target riscv32imac-unknown-none-elf --verbose --profile release

      - name: Clippy
        run: cargo clippy --target riscv32imac-unknown-none-elf --verbose --all-features --workspace -- -D warnings

      - name: Audit
        run: cargo audit
